[tool.pytest.ini_options]
pythonpath = "src"
markers = [
    "local",  # marks tests that rely on local files
    "s3",     # marks tests that require AWS S3 access
]

[[tool.mypy.overrides]]
module = ["dash.*", "dash_mantine_components.*", "boto3.*", "plotly.*", "dash_iconify.*"]
ignore_missing_imports = true
